name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "Features 🚀"
    labels:
      - "feature"
      - "feat"
      - "enhancement"
  - title: "Bug Fixes 🐛"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "Maintenance 🧰"
    labels:
      - "chore"
      - "docs"
      - "documentation"
exclude-labels:
  - 'skip-changelog'
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## What’s Changed 🔥
  $CHANGES
  
  ## Contributors 👏
  $CONTRIBUTORS
  
  ## Previous versions 🗄️
  $PREVIOUS_TAG