name: minidonkey
description: A mini donkey to help carry messages securely and secretly.
version: 1.0.7+16
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.6.4
  image_gallery_saver: ^1.2.2
  esys_flutter_share: ^1.0.2
  image: ^2.1.19
  permission_handler: ^5.1.0+2
  encrypt: ^4.0.0
  provider: ^4.0.4
  http: ^0.12.0+4
  device_info: ^0.4.2+1
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  mockito: ^4.1.1
  path_provider: ^1.0.0
  hive_generator: ^0.7.0+2
  build_runner: ^1.10.0
dependency_overrides:
  path: ^1.8.0
  dartx: ^0.5.0
  intl: ^0.17.0
  typed_data: ^1.3.0
  intl_translation: ^0.17.10
  crypto: ^3.0.0
  clock: ^1.1.0
  collection: ^1.15.0
  archive: ^3.0.0
flutter:
  assets:
    - "assets/photo_placeholder.png"
    - "assets/loading_deer.gif"
    - "assets/loading_donkey.gif"
    - "assets/loading_husky.gif"
    - "assets/message_logo.png"
    - "assets/rabbits_clapping.gif"
    - "assets/bear_bye.gif"
    - "assets/in_love_corgi_long.gif"
    - "assets/programming_corgi.gif"
    - "assets/test_images/corgi.png"
    - "assets/test_images/encrypted_corgi.png"
  uses-material-design: true
