name: Integration Test Android
on:
  pull_request:
    branches:
      - "master"
    paths:
      - "photochatapp/*"
      - ".github/workflows/integration-test-android.yml"
  schedule:
    - cron: 0 2 * * *
jobs:
  integration-test-android:
    name: run integration test on Android emulator
    runs-on: macos-latest
    strategy:
      matrix:
        device:
          - "pixel_xl"
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: install local actions
        run: bash ./scripts/install_action_dependencies.sh
      - uses: actions/setup-java@v1
        with:
          java-version: '8.x'
      - uses: ./actions/get_ci_versions
        id: get_ci_versions
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ steps.get_ci_versions.outputs.flutter_version }}
          channel: ${{ steps.get_ci_versions.outputs.flutter_channel }}
      - name: upgrade flutter to dev latest
        run: |
          flutter channel master
          flutter upgrade
          flutter --version
      - name: run tests
        timeout-minutes: 30
        uses: reactivecircus/android-emulator-runner@v2.6.0
        env:
          ANDROID_SIGN_PWD: ${{ secrets.ANDROID_SIGN_PWD }}
          SECRET_REPO: ${{ secrets.SECRET_REPO }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          api-level: 28
          profile: ${{ matrix.device }}
          script: /Users/runner/Library/Android/sdk/tools/bin/avdmanager list && sleep 20 && ./scripts/setenv.sh && cd ./photochatapp && flutter doctor -v && flutter pub get && flutter drive --target=test_driver/app.dart
      - name: upload screenshot
        uses: actions/upload-artifact@master
        with:
          name: online_screenshot_${{ matrix.device }}
          path: /tmp/iwfpapp_screenshot
