name: Integration Test iOS
on:
  pull_request:
    branches:
      - "master"
    paths:
      - "photochatapp/*"
      - ".github/workflows/integration-test-ios.yml"
  schedule:
    - cron: 0 2 * * *
jobs:
  integration-test-ios:
    name: run integration test on iOS emulator
    runs-on: macos-latest
    strategy:
      matrix:
        device:
          - "iPad Pro (12.9-inch) (4th generation) (13.7)"
          - "iPhone 11 Pro Max (13.7)"
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: Monorepo-Actions/config-for-actions@main
        id: get_action_configs
        with:
          config_files: ./configs/actions_config.json
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ steps.get_action_configs.outputs.flutter_version }}
          channel: ${{ steps.get_action_configs.outputs.flutter_channel }}
      - name: upgrade flutter
        run: |
          flutter channel master
          flutter upgrade
      - name: list all simulators
        run: xcrun instruments -s
      - name: start simulator
        run: |
          UDID=$(
            xcrun instruments -s |
            awk \
              -F ' *[][]' \
              -v 'device=${{ matrix.device }}' \
              '$1 == device { print $2 }'
          )
          xcrun simctl boot "${UDID:?No Simulator with this name found}"
      - name: run integration tests
        timeout-minutes: 30
        env:
          ANDROID_SIGN_PWD: ${{ secrets.ANDROID_SIGN_PWD }}
          SECRET_REPO: ${{ secrets.SECRET_REPO }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          ./scripts/setenv.sh
          cd ./photochatapp
          flutter doctor -v
          flutter pub get
          xcrun simctl io booted recordVideo recording.mov &
          sleep 5
          export RECORDING_PID=${!}
          echo "Recording process up with pid: ${RECORDING_PID}"
          flutter drive --target=test_driver/app.dart
          sleep 5
          kill -SIGINT $RECORDING_PID
          sleep 10
          cp recording.mov /tmp/iwfpapp_screenshot
      - name: upload screenshot
        uses: actions/upload-artifact@master
        with:
          name: online_screenshot_${{ matrix.device }}
          path: /tmp/iwfpapp_screenshot
