name: Release iOS app
on:
  push:
    branches:
      - "master"
    tags:
      - "v*"
jobs:
  release-ios:
    name: release ios app
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.12.13+hotfix.5"
          channel: "stable"
      - name: upgrade flutter
        run: |
          flutter channel stable
          flutter upgrade
      - name: install gem packages
        run: |
          cd photochatapp/ios
          gem install bundler:1.17.3
          bundle install
      - name: build verification
        run: |
          cd photochatapp
          flutter build ios --release --no-codesign
      - name: upload to testfight
        run: echo "iOS app releasing has been suspended since Apple appstore does not support continuous deployment"
