name: Unit Test App
on:
  push:
    paths:
      - "photochatapp/*"
  pull_request:
    branches:
      - "master"
  schedule:
    - cron: 0 2 * * *
jobs:
  unit-test-app:
    name: run app tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.13+hotfix.8'
          channel: 'stable'
      - name: check flutter status
        run: |
          flutter --version
          flutter doctor -v
      - name: install flutter dependencies for stable flutter
        run: |
          cd ./photochatapp
          flutter pub get
      - name: static analyze code with stable flutter
        run: |
          cd ./photochatapp
          flutter analyze
      - name: run unit tests against stable flutter
        run: |
          cd ./photochatapp
          flutter test
      - name: upgrade flutter to the bleeding edge version
        run: |
          flutter channel master
          flutter upgrade
      - name: check flutter status
        run: |
          flutter --version
          flutter doctor -v
      - name: install flutter dependencies for bleeding edge flutter
        run: |
          cd ./photochatapp
          flutter pub get
      - name: static analyze code with bleeding edge flutter
        run: |
          cd ./photochatapp
          flutter analyze
      - name: run unit tests against bleeding edge flutter
        run: |
          cd ./photochatapp
          flutter test
